version: '3.9'
services:
  postgres:
    container_name: spring-boot-postgres
    image: postgres:15.1-alpine3.16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgres/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret

volumes:
  pgdata: